services:
  frontend:

    image: amarbhise/intbuddy-frontend:latest

    container_name: intbuddy-frontend

    restart: unless-stopped

    expose:
      - "80"

    networks:
      - intbuddy-network

networks:
  intbuddy-network:
    external: true
